### ISSUE TITLE
SQL lite error during first run

### ISSUE THREAD

**Issue by fredzannarbor** [pooleja/TranscodeE16#2]
```
fred@fred-XPS-L322X:~/pagekicker-21/TranscodeE16$ python3 transcodeE16-server.py -d
Connecting to DB.
Traceback (most recent call last):
  File "transcodeE16-server.py", line 47, in <module>
    sql = TranscodeJobsSQL()
  File "/home/fred/pagekicker-21/TranscodeE16/sqldb.py", line 30, in __init__
    self.conn = sqlite3.connect(DATABASE_FILE, check_same_thread=False)
sqlite3.OperationalError: unable to open database file
fred@fred-XPS-L322X:~/pagekicker-21/TranscodeE16$ sudo 
```

**Comment by pooleja** [comment]
Hi @fredzannarbor, did you run the setup script before running the server python file?
